### ISSUE TITLE
Incorect sysfs file is used for backlight control

### ISSUE THREAD

**Issue by hacker1024** [ubports/repowerd#11]
I'm porting Ubuntu Touch to the Xiaomi Redmi K20 Pro. There are two subdirectories in `/sys/class/backlight` on my device - `backlight`, and `panel0-backlight`. `panel0-backlight` is the display backlight.

Repowerd's [current method](https://github.com/ubports/repowerd/blob/3909fb6b7bc5c5405b2ee1ad22e931907d7d05db/src/adapters/sysfs_backlight.cpp#L73) of choosing the sysfs file to control the backlight with is to iterate through the subdirectories in `/sys/class/backlight`, looking for one with a `brightness` file.

In my case, this applies to both subdirectories. `backlight` comes before `panel0-backlight` alphebetically, so the former is used instead of the latter - which is not what should happen.

To fix this, I have two suggestions:
1) Code some sort of prioritisation logic, to make sure the right backlight device is chosen, or
2) Let the path be configured in a config file.

1 seems cleaner (if it can be done), as it should work automatically.

**Comment by Flohack74** [comment]
Ok that was bad I basically described option 2 here and now I read it fully. Yes option 1 would be cleaner, but the question is, would other devices need different priorities? We could try to do it (Doing the same for torchlight now already). And see how far we can get 👍

**Comment by hacker1024** [comment]
I think it's unlikely that a device named `panel0-backlight` would be anything other than the display backlight on any device, so I think trying it should be fine?

It's kind of weird that I'm the only one (as far as I can tell) that's ran into this issue - it feels a little wrong to add sorting code that would execute on every device just to fix just one reported outlier (but I suppose reading from the config file would actually be even less performant).

(P.S. - I don't know C, so, unfortunately, I can't make a PR myself either way.)

**Comment by peat-psuwit** [comment]
Hello,

Thank you for contributing to UBports. As part of project renaming and the effort to port Ubuntu Touch stack to Ubuntu 20.04, we're incrementally migrating repositories to GitLab.

Your issue is now migrated to:
https://gitlab.com/ubports/core/repowerd/-/issues/11

Sorry for your inconvenience.
