### ISSUE TITLE
Consider merging improvements from repowerd LP master

### ISSUE THREAD

**Issue by afrantzis** [ubports/repowerd#2]
Hi! The master branch of repowerd in launchpad contains some fixes that I think are worth applying to the ubports version:

adapters: Ensure dimming a lit display will not increase its brightness
https://git.launchpad.net/repowerd/commit/?id=56c2aa857ad1c2bfe0e393db4186f7370d5e0f5b

adapters: Fix application of user-set normal brightness value
https://git.launchpad.net/repowerd/commit/?id=d433783f73fcc3641b2182a6ee2171fa422e0c52

adapters: Improve critical battery behavior
https://git.launchpad.net/repowerd/commit/?id=e97861208ea6f547f03abdaa6588e0e0391a6acc

adapters: Generate random cookies for wakeup requests
https://git.launchpad.net/repowerd/commit/?id=3510a4626429cb46cc5b4345b27f60d9af8b55e4

Some of the changes may need some rework, since they may be based on renamed or new classes (e.g. UPowerPowerSource -> UPowerPowerSourceAndLid). I had extensively tested these changes back then, but only in the context of the repowerd LP master branch which contains major changes vs ubports (e.g., multi user/session support), so some care and testing should be taken when applying these here.

**Comment by Flohack74** [comment]
Thanks for the suggestions! Are you basically interested in doing this yourself maybe? =)

**Comment by afrantzis** [comment]
I didn't offer to create the PRs myself because I am unable to perform any proper device testing (I only have a single device, which is my daily driver, so I can't afford development on it). That being said, as long as it is clear that no ubports device testing has been performed on my side, and you are fine with this, I could create the PRs.

**Comment by Flohack74** [comment]
Yes, I can test for you, or the QA team. We will get this managed.

**Comment by afrantzis** [comment]
Hmm, I just realized that 2017.03 (LP master), including all the fixes mentioned above, has been already pulled in https://github.com/ubports/repowerd/tree/xenial_-_new-version . So, it's just a matter of using that branch. Closing this issue for now. If there is no plan to move to that branch soon we can consider reopening and cherry-picking the changes.

**Comment by Flohack74** [comment]
Ah OK I see ;)
