### ISSUE TITLE
Invalid cross-device link during update

### ISSUE THREAD

**Issue by qianjiaqiang** [ubports/repowerd#21]
Update repowerd-data/xenial from : 2018.03+1ubports1+0~ 20190409235621.9 ~1.gbp2f36d3  

to :  repowerd-data/xenial 2018.04+ubports+0~ 20200908163621.6 ~1.gbp5c9e02

Error message of apt is : 

> unable to make backup link of './usr/share/powerd/device_configs/config-default.xml' before installing new version: Invalid cross-device link

**Comment by dobey** [comment]
Using apt to update the system is not supported. Ubuntu Touch uses image based updates for the system, and a read-only rootfs for various reasons.
